name: CI
on:
  push:
    branches: ["*"]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "docs/vercel/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "docs/vercel/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          default: true
          profile: minimal
          components: clippy

      - name: Build Debug
        run: |
          rustc --version
          cargo build --features=fail-on-deprecated

      - name: Run tests
        run: cargo test

      - name: Run clippy
        run: cargo clippy

      - name: Run onefetch
        run: cargo run

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt 
        run: cargo fmt -- --check

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          override: true

      - name: Install cargo-tarpaulin
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: latest

      - name: Coverage with tarpaulin
        run: cargo tarpaulin --out Lcov -- --test-threads 1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
