name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v3

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          default: true
          profile: minimal
          components: clippy

      - name: Build Debug
        run: |
          rustc --version
          cargo build --features=fail-on-deprecated

      - name: Run tests
        run: cargo test

      - name: Run clippy
        run: cargo clippy

      - name: Debug
        run: "cat .git/HEAD; git cat-file -p a802f89fc823c6c8cf2467c2b7908e1d78e8b755"
      - name: Run onefetch
        run: cargo run

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt -- --check
